from typing import Optional, List

from pydantic import BaseModel, Field


class Category(BaseModel):
    id: Optional[str] = Field(default=None, description="The category's ID (will be generated by the database)")
    name: str = Field(..., description="The category name in English")
    nameAr: str = Field(..., description="The category name in Arabic")

    class Config:
        schema_extra = {
            "example": {
                "name": "Comedy",
                "nameAr": "كوميديا",
            }
        }


class CategoriesList(BaseModel):
    data: List[Category]

    class Config:
        schema_extra = {
            "example": [
                {
                    "id": "123",
                    "name": "Comedy",
                    "nameAr": "كوميديا",
                },
                {
                    "id": "123",
                    "name": "Drama",
                    "nameAr": "دراما",
                }
            ]
        }
