import datetime
from typing import Optional, List

from pydantic import BaseModel, Field


class Short(BaseModel):
    shortId: Optional[str] = Field(default=None, description="The short's ID (will be generated by the database)")
    text: str = Field(..., description="The short's text")
    type: str = Field(..., description="The short's type (short, anecdote, confession, quote)")
    isAnon: Optional[bool] = Field(default=True, description="is this the writer's anonymous?")
    writerId: Optional[str] = Field(None, description="The writer's id (If not anonymous)")
    tiktokId: Optional[str] = Field(None, description="The writer's tiktok id")
    isHidden: Optional[bool] = Field(default=False, description="is this the short hidden?")
    votes: Optional[int] = Field(default=0, description="The short's votes")
    createdAt: Optional[str] = Field(default=str(datetime.datetime.utcnow()), description="The time of story creation")

    class Config:
        schema_extra = {
            "example": {
                "text": "My short",
                "type": "confession",
                "isAnon": True,
                "tiktokId": "@SSWWW",
            }
        }


class ShowShorts(BaseModel):
    data: List[Short]

    class Config:
        schema_extra = {
            "example": [
                {
                    "shortId": "123",
                    "text": "My short",
                    "createdAt": "01/01/1990",
                    "type": "confession",
                    "isAnon": True,
                    "tiktokId": "@SSWWW",
                    "writerId": None,
                    "isHidden": False,
                    "votes": 0,
                },
                {
                    "shortId": "111",
                    "text": "My short",
                    "createdAt": "01/01/1990",
                    "type": "confession",
                    "isAnon": True,
                    "tiktokId": "@SSWWW",
                    "writerId": None,
                    "isHidden": False,
                    "votes": 0,
                }
            ]
        }
